[package]
name = "lua-dream-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
lua-dream-lexer = { workspace = true }
strum = { version = "0.27.2", features = ["derive"] }
thiserror = { workspace = true }
